### ISSUE TITLE
Typo for config.cfg

### ISSUE THREAD

**Issue by thecrackofdawn** [microsoftgraph/microsoft-graph-training#103] opened 2022-07-11 03:06 UTC
![image](https://user-images.githubusercontent.com/6297397/178180987-f62a78e1-c05c-4bdc-9732-b3417e884c8e.png)
graphUserScopes should be like `User.Read Mail.Read Mail.Send`.
Currently in `Azure Identity client library for Python` scopes are case sensitive.

**Comment by jasonjoh** [comment] 2022-07-29 13:25
Hi @thecrackofdawn, sorry this gave you trouble. I've retested this again with the lower-cased scopes, and it worked fine. Do you mind giving details on what error you saw, what OS you're on, and what version of Python?

**Comment by thecrackofdawn** [comment] 2022-08-02 06:11
The version of msal I am using is 1.18.0.  This [method](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/01b3722aee254270ad25422422b61d02e4395f9e/msal/application.py#L1124) will try to get token from cache first. However, if you write your scopes in lower case, you can't reuse the cached token. This is because scopes are case sensitive in msal. You can check the method [`find(self, credential_type, target=None, query=None)`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/01b3722aee254270ad25422422b61d02e4395f9e/msal/token_cache.py#L85) in TokenCache. When you write your scopes like `user.read`, the value of paramter `target` is  `user.read`, the scopes of the cached token is `User.Read`.
In the example you give, I will be asked to relogin after several requests been made. After you launch the example, you can try to input `2` (2. List my inbox) to list your inbox several times to see if you will be asked to relogin.

**Comment by jasonjoh** [comment] 2022-08-10 18:17
I've tried to reproduce this as you describe and cannot. I listed the inbox 20 times with no issue. I also waited over an hour to ensure that the token would expire (requiring a refresh) and it still worked for me. For information purposes, I'm running this on Ubuntu with Python 3.10.4.

I've tested it with the capitalized versions as well, and since both work for me I'll go ahead and update it.

**Comment by jasonjoh** [comment] 2022-08-10 18:27
Changes have propagated to live site. Closing issue.

**Closed by jasonjoh** 2022-08-10 18:27 UTC
