### ISSUE TITLE
Cannot import name 'GraphRequestAdapter' from 'msgraph'

### ISSUE THREAD

**Issue by techge** [microsoftgraph/microsoft-graph-training#132] opened 2023-01-18 15:18 UTC
I tried this tutorial part https://learn.microsoft.com/en-us/graph/tutorials/python-app-only?tabs=aad but can not import GraphRequestAdapter

```
from msgraph import GraphRequestAdapter, GraphServiceClient
ImportError: cannot import name 'GraphRequestAdapter' from 'msgraph' (/home/user/venv/lib/python3.10/site-packages/msgraph/__init__.py)
```

Did there change something or what might be wrong? I installed the prerequesites as needed:

```
python3 -m pip install azure-identity
python3 -m pip install msgraph-core
```

**Comment by techge** [comment] 2023-01-18 16:11
Mh, might be some version confusion?

https://github.com/microsoftgraph/msgraph-sdk-python-core/pull/141/commits/b576910d3ad21d4f9d0097b8623500a238997d50

I am using python 3.10, might related?

**Comment by jasonjoh** [comment] 2023-01-27 14:56
@techge what version of msgraph-sdk are you using? I just updated this yesterday (also using 3.10) and had no issues importing. I'm using latest preview of msgraph-sdk: 1.0.0a9.

**Comment by jasonjoh** [comment] 2023-02-01 16:20
I believe this is caused by an error in the instructions. Instead of `msgraph-core`, you should install `msgraph-sdk`. I will get this fixed in the tutorial.

**Comment by jasonjoh** [comment] 2023-02-01 16:38
Let me know if this didn't fix your issue.

**Closed** 2023-02-01 16:37 UTC

**Comment by techge** [comment] 2023-02-02 10:26
Fixed it indeed, thanks a lot!
